repos:
- repo: local
  hooks:
  - id: scan-secrets
    name: Scan secrets
    entry: bash
    args: ["-c", "check=staged-changes ./scripts/githooks/scan-secrets.sh"]
    language: system
    pass_filenames: false
  - id: check-file-format
    name: Check file format
    entry: bash
    args: ["-c", "check=staged-changes ./scripts/githooks/check-file-format.sh"]
    language: system
    pass_filenames: false
  - id: check-markdown-format
    name: Check Markdown format
    entry: bash
    args: ["-c", "check=staged-changes ./scripts/githooks/check-markdown-format.sh"]
    language: system
    pass_filenames: false
  - id: check-english-usage
    name: Check English usage
    entry: bash
    args: ["-c", "check=staged-changes ./scripts/githooks/check-english-usage.sh"]
    language: system
    pass_filenames: false
  - id: lint-terraform
    name: Lint Terraform
    entry: ./scripts/githooks/check-terraform-format.sh
    language: script
    pass_filenames: false
  - id: python-linting-and-formatting
    name: Python linting and formatting
    entry: ./scripts/githooks/python-lint-and-format.sh
    language: script
    pass_filenames: false
