name: "Test stage"

env:
  BASE_URL: "http://localhost:5001"
  HOSTNAME: "localhost"

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  create-coverage-name:
    name: "Create coverage artefact name"
    runs-on: ubuntu-latest
    outputs:
      coverage-name: ${{ steps.create_name.outputs.artefact-name }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - id: create_name
        name: "Generate unique coverage artefact name"
        uses: ./.github/actions/create-artefact-name
        with:
          prefix: coverage

  test-unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Run unit test suite"
        run: make test-unit
      - name: "Upload unit test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: unit-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Publish unit test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/unit-tests.xml

  test-contract:
    name: "Contract tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Start local Lambda"
        uses: ./.github/actions/start-local-lambda
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Run contract tests"
        run: make test-contract
      - name: "Upload contract test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: contract-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Publish contract test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/contract-tests.xml

  test-schema:
    name: "Schema validation tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Start local Lambda"
        uses: ./.github/actions/start-local-lambda
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Run schema validation tests"
        run: make test-schema
      - name: "Upload schema test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: schema-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Publish schema test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/schema-tests.xml

  test-integration:
    name: "Integration tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Start local Lambda"
        uses: ./.github/actions/start-local-lambda
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Run integration test"
        run: make test-integration
      - name: "Upload integration test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: integration-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Publish integration test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/integration-tests.xml

  test-acceptance:
    name: "Acceptance tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Start local Lambda"
        uses: ./.github/actions/start-local-lambda
        with:
          python-version: ${{ inputs.python_version }}
          max-seconds: 90
      - name: "Run acceptance test"
        run: make test-acceptance
      - name: "Upload acceptance test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: acceptance-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Publish acceptance test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/acceptance-tests.xml

  merge-test-coverage:
    name: "Merge test coverage"
    needs: [create-coverage-name, test-unit, test-contract, test-schema, test-integration, test-acceptance]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Download all test coverage artefacts"
        uses: actions/download-artifact@v6
        with:
          path: pathology-api/test-artefacts/
          merge-multiple: false
      - name: "Merge coverage data"
        run: make test-coverage
      - name: "Rename coverage XML with unique name"
        run: |
          cd pathology-api/test-artefacts
          mv coverage-merged.xml ${{ needs.create-coverage-name.outputs.coverage-name }}.xml
      - name: "Upload combined coverage report"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ needs.create-coverage-name.outputs.coverage-name }}
          path: pathology-api/test-artefacts
          retention-days: 30

  sonarcloud-analysis:
    name: "SonarCloud Analysis"
    needs: [create-coverage-name, merge-test-coverage]
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Full history is needed for better analysis
      - name: "Download merged coverage report"
        uses: actions/download-artifact@v6
        with:
          name: ${{ needs.create-coverage-name.outputs.coverage-name }}
          path: coverage-reports/
      - name: "SonarCloud Scan"
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANISATION_KEY }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.python.coverage.reportPaths=coverage-reports/${{ needs.create-coverage-name.outputs.coverage-name }}.xml
